  (
    org.login in (
      'kubernetes', 'prometheus', 'opentracing', 'fluent', 'linkerd', 'grpc', 'containerd', 'devspace-sh',
      'rkt', 'kubernetes-client', 'kubernetes-helm', 'nats-io', 'open-policy-agent', 'spiffe',
      'kubernetes-incubator', 'coredns', 'grpc-ecosystem', 'containernetworking', 'cncf', 'getsops',
      'envoyproxy', 'jaegertracing', 'theupdateframework', 'rook', 'vitessio', 'crosscloudci',
      'cloudevents', 'openeventing', 'telepresenceio', 'helm', 'goharbor', 'kubernetes-csi',
      'etcd-io', 'tikv', 'cortexproject', 'buildpack', 'falcosecurity', 'OpenObservability',
      'dragonflyoss', 'virtual-kubelet', 'Virtual-Kubelet', 'kubeedge', 'brigadecore', 'pixie-io',
      'kubernetes-sig-testing', 'kubernetes-providers', 'kubernetes-addons', 'kubernetes-test',
      'kubernetes-extensions', 'kubernetes-federation', 'kubernetes-security', 'kubernetes-sigs',
      'kubernetes-sidecars', 'kubernetes-tools', 'cdfoundation', 'cri-o', 'networkservicemesh',
      'open-telemetry', 'openebs', 'thanos-io', 'fluxcd', 'in-toto', 'strimzi', 'kubevirt', 'cubefs',
      'longhorn', 'chubaofs', 'kedacore', 'servicemeshinterface', 'argoproj', 'volcano-sh', 'v6d-io',
      'cni-genie', 'keptn', 'kudobuilder', 'cloud-custodian', 'dexidp', 'artifacthub', 'parallaxsecond',
      'bfenetworks', 'crossplane', 'crossplaneio', 'litmuschaos', 'projectcontour', 'operator-framework',
      'chaos-mesh', 'serverlessworkflow', 'wayfair-tremor', 'metal3-io', 'openservicemesh', 'tremor-rs',
      'getporter', 'keylime', 'backstage', 'schemahero', 'cert-manager', 'openkruise', 'kruiseio',
      'tinkerbell', 'pravega', 'kyverno', 'buildpacks', 'gitops-working-group', 'piraeusdatastore',
      'curiefense', 'distribution', 'kubeovn', 'AthenZ', 'openyurtio', 'ingraind', 'tricksterproxy',
      'foniod', 'emissary-ingress', 'kuberhealthy', 'WasmEdge', 'chaosblade-io', 'fluid-cloudnative',
      'submariner-io', 'argoproj-labs', 'trickstercache', 'skooner-k8s', 'antrea-io', 'pixie-labs',
      'layer5io', 'oam-dev', 'kube-vip', 'service-mesh-performance', 'krator-rs', 'oras-project',
      'wasmCloud', 'wascc', 'wascaruntime', 'waxosuit', 'kumahq', 'k8gb-io', 'cdk8s-team', 'metallb',
      'karmada-io', 'superedge', 'cilium', 'project-akri', 'dapr', 'open-cluster-management-io',
      'nocalhost', 'kubearmor', 'k8up-io', 'kube-rs', 'k3s-io', 'vscode-kubernetes-tools', 'devfile',
      'meshery', 'knative', 'knative-sandbox', 'FabEdge', 'confidential-containers', 'OpenFunction',
      'clusterpedia-io', 'aeraki-mesh', 'aeraki-framewoirk', 'opencurve', 'open-feature', 'krkn-chaos',
      'openfeatureflags', 'kubewarden', 'chimera-kube', 'devstream-io', 'kubedl-io', 'kubevela',
      'hexa-org', 'konveyor', 'external-secrets', 'krustlet', 'crossplane-contrib', 'Serverless-Devs',
      'ServerlessTool', 'ContainerSSH', 'openfga', 'lima-vm', 'k14s', 'kubereboot', 'istio', 'kserve',
      'inclavare-containers', 'notaryproject', 'merbridge', 'devspace-cloud', 'covexo', 'tellerops',
      'project-zot', 'paralus', 'carina-io', 'ko-build', 'opcr-io', 'werf', 'kubescape', 'openelb',
      'opencost', 'carvel-dev', 'inspektor-gadget', 'clusternet', 'sealerio', 'keycloak', 'armadaproject',
      'headlamp-k8s', 'slimtoolkit', 'sockerslim', 'sustainable-computing-io', 'pipe-cd', 'xline-kv',
      'hwameistor', 'microcks', 'kubeclipper', 'kubeclipper-labs', 'kubeflow', 'buildpacks-community',
      'eraser-dev', 'knative-extensions', 'project-copacetic', 'kube-logging', 'kanisterio', 'kcp-dev',
      'kcl-lang', 'projectcapsule', 'kube-burner', 'kuasar-io', 'redchat-chaos', 'kubestellar',
      'megaease', 'spidernet-io', 'k8sgpt-ai', 'chaos-kubox', 'KubeStellar', 'kptdev', 'redhat-chaos',
      'OpenMetrics', 'openmetrics', 'open-gitops', 'kubeslice', 'connectrpc', 'kairos-io', 'c3os-io',
      'kubean-io', 'koordinator-sh', 'radius-project', 'easegress-io', 'bank-vaults', 'runatlantis',
      'project-stacker', 'oscal-compass', 'Kuadrant', 'openGemini', 'score-spec', 'bpfman', 'bpfd-dev',
      'loxilb-io', 'perses', 'ratify-project', 'Project-HAMi', 'shipwright-io', 'flatcar', 'flatcar-linux',
      'KusionStack', 'cartography-cncf', 'cncf-tags', 'youki-dev', 'kaito-project', 'sermant-io',
      'kmesh-net', 'ovn-org', 'prometheus-community', 'tratteria', 'spinkube', 'k0sproject', 'interlink-hq',
      'cloudnative-pg', 'podman-desktop', 'drasi-project', 'ovn-kubernetes', 'kgateway-dev', 'k8sgateway',
      'hyperlight-dev', 'cozystack', 'kitops-ml', 'SlimPlanet', 'spinframework', 'container2wasm',
      'runmedev', 'tokenetes', 'bootc-dev', 'composefs', 'kubefleet-dev', 'meshery-extensions',
      'opentofu', 'opentffoundation', 'openterraform', 'cadence-workflow', 'kagent-dev', 'urunc-dev',
      'xregistry', 'CloudNativeAI', 'modelpack', 'oauth2-proxy', 'oxia-db', 'cedar-policy', 'project-dalec'
    )
    or repo.name in (
      'docker/containerd', 'coreos/rkt', 'GoogleCloudPlatform/kubernetes', 'cncf/sig-app-delivery',
      'lyft/envoy', 'uber/jaeger', 'BuoyantIO/linkerd', 'apcera/nats', 'apcera/gnatsd',
      'docker/notary', 'youtube/vitess', 'appc/cni', 'miekg/coredns', 'coreos/rocket',
      'rktproject/rkt', 'datawire/telepresence', 'RichiH/OpenMetrics', 'vmware/harbor',
      'coreos/etcd', 'pingcap/tikv', 'weaveworks/cortex', 'weaveworks/prism', 'cncf/tag-app-delivery',
      'weaveworks/frankenstein', 'draios/falco', 'alibaba/Dragonfly', 'Azure/brigade',
      'ligato/networkservicemesh', 'improbable-eng/promlts', 'improbable-eng/thanos',
      'weaveworks/flux', 'EnMasseProject/barnabas', 'ppatierno/barnabas',' ppatierno/kaas',
      'rancher/longhorn', 'containerfs/containerfs.github.io', 'containerfilesystem/cfs',
      'containerfilesystem/doc-zh', 'tomkerkhove/sample-dotnet-queue-worker', 'pusher/oauth2_proxy',
      'tomkerkhove/sample-dotnet-queue-worker-servicebus-queue', 'plunder-app/kube-vip',
      'tomkerkhove/sample-dotnet-worker-servicebus-queue', 'deislabs/smi-spec', 'loft-sh/devspace',
      'deislabs/smi-sdk-go', 'deislabs/smi-metrics', 'deislabs/smi-adapter-istio', 'herbrandson/k8dash',
      'deislabs/smi-spec.io', 'capitalone/cloud-custodian', 'coreos/dex', 'Kong/kuma',  'Kong/kuma-website',
      'Kong/kuma-demo', 'Kong/kuma-gui', 'Kong/kumacut', 'docker/pasl', 'baidu/bfe', 'Huawei-PaaS/CNI-Genie',
      'patras-sdk/kubebuilder-maestro', 'patras-sdk/maestro', 'maestrosdk/maestro', 'maestrosdk/frameworks',
      'openebs/test-storage', 'openebs/litmus', 'cncf/hub', 'heptio/contour', 'chaos-mesh/chaos-mesh',
      'cncf/wg-serverless-workflow', 'spotify/backstage', 'deislabs/porter', 'alibaba/openyurt',
      'mit-ll/python-keylime', 'mit-ll/keylime', 'awslabs/cdk8s', 'jeststack/cert-manager',
      'jetstack-experimental/cert-manager', 'packethost/tinkerbell', 'nirmata/kyverno', 'indeedeng/k8dash',
      'yahoo/athenz', 'indeedeng/k8dash-website', 'alauda/kube-ovn', 'redsift/ingraind', 'Comcast/kuberhealthy',
      'AbsaOSS/k8gb', 'AbsaOSS/ohmyglb', 'Comcast/trickster', 'datawire/ambassador', 'alibaba/v6d',
      'alibaba/libvineyard', 'vmware-tanzu/antrea', 'cheyang/fluid', 'rancher/submariner', 'alibaba/kubedl',
      'deislabs/krustlet', 'deislabs/oras', 'shizhMSFT/oras', 'docker/distribution', 'second-state/SSVM',
      'deislabs/akri', 'danderson/metallb', 'google/metallb', 'alibaba/inclavare-containers',
      'noironetworks/cilium-net', 'kubesphere/openelb', 'kubesphere/porterlb', 'kubesphere/porter',
      'Azure/vscode-kubernetes-tools', 'accuknox/KubeArmor', 'vshn/k8up', 'clux/kube-rs',
      'clux/kubernetes-rust', 'che-incubator/devworkspace-api', 'alibaba/sealer', 'SpectralOps/teller',
      'SpectralOps/helm-teller', 'SpectralOps/setup-teller-action', 'merico-dev/stream', 'merico-dev/OpenStream',
      'fusor/mig-operator', 'G-Research/armada', 'janoszen/ContainerSSH', 'janoszen/containerssh',
      'weaveworks/kured', 'vmware-tanzu/carvel', 'vmware-tanzu/carvel-kapp-controller',
      'vmware-tanzu/carvel-kapp', 'vmware-tanzu/carvel-ytt', 'vmware-tanzu/carvel-imgpkg',
      'vmware-tanzu/carvel-kbld', 'vmware-tanzu/carvel-vendir', 'vmware-tanzu/carvel-kwt',
      'vmware-tanzu/carvel-secretgen-controller', 'AkihiroSuda/lima', 'kebe7jun/mepf', 'kebe7jun/mebpf',
      'anuvu/zot', 'google/ko', 'flant/werf', 'flant/dapp', 'flant/dapper', 'armosec/kubescape',
      'kinvolk/inspektor-gadget', 'clastix/capsule', 'clastix/capsule-proxy', 'clastix/capsule-addon-rancher',
      'clastix/capsule-community', 'clastix/capsule-addon-cloudcasa', 'clastix/capsule-k8s-charm',
      'clastix/clastix/capsule-lens-extension', 'clastix/capsule-helm-chart', 'clastix/flux2-capsule-multi-tenancy',
      'clastix/capsule-ns-filter', 'clastix/Capsule', 'clastix/ckd-capsule-app', 'mozilla/sops', 'mozilla/sotp',
      'mozilla-services/sosp', 'kinvolk/headlamp', 'cloudimmunity/docker-slim', 'Azure/eraser', 'datenlord/Xline',
      'GoogleContainerTools/kpt', 'google/kubeflow', 'banzaicloud/logging-operator', 'cloud-bulldozer/kube-burner',
      'cloud-bulldozer/rosa-burner', 'cloud-bulldozer/krkn', 'cloud-bulldozer/kraken', 'openshift-scale/kraken',
      'kcp-dev/edge-mc', 'bufbuild/connect-go', 'bufbuild/rerpc', 'rerpc/rerpc', 'mudler/c3os', 'banzaicloud/bank-vaults',
      'banzaicloud/vault-dogsbody', 'atlantisnorth/atlantis', 'anuvu/stacker', 'IBM/compliance-trestle',
      '3scale-labs/authorino', 'redhat-et/bpfd', 'lyft/cartography', 'deislabs/ratify', 'deislabs/ratify-web',
      'deislabs/ratify-action', 'redhat-developer/build', 'redhat-developer/buildv2',
      'redhat-developer/buildv2-operator', 'kinvolk/Flatcar', 'kinvolk/flatcar-scripts', 'kinvolk/mantle',
      'containers/youki', 'utam0k/youki', 'Azure/kaito', 'huaweicloud/Sermant', 'huaweicloud/java-mesh',
      'huaweicloud/JavaMesh', 'openvswitch/ovn-kubernetes', 'fermyon/spin', 'fermyon/spin-python-sdk',
      'fermyon/spin-js-sdk', 'fermyon/spin-rust-sdk', 'fermyon/spin-dotnet-sdk', 'fermyon/spin-nim-sdk',
      'fermyon/spin-plugins', 'fermyon/spin-test', 'fermyon/platform-plugin', 'AxaFrance/SlimFaas',
      'fermyon/spin-trigger-command', 'fermyon/spin-trigger-sqs', 'fermyon/spin-trigger-cron',
      'ktock/container2wasm', 'stateful/runme', 'stateful/runme.dev', 'stateful/runmejs',
      'stateful/runme-web-extension', 'stateful/runme-action', 'stateful/docs.runme.dev',
      'stateful/runme-action-examples', 'stateful/mkdocs-runme-plugin', 'stateful/Runme-CDEs',
      'stateful/runme-terramate-aws', 'stateful/terramate-runme-example', 'uber/cadence',
      'stateful/runme-terramate-example', 'stateful/runme-foyle-ai', 'Azure/Fleet-PRSE',
      'Azure/fleet-networking', 'Azure/fleet', 'Azure/azure-rest-api-specs-fleet',
      'containers/podman', 'containers/buildah', 'containers/skopeo', 'containers/netavark',
      'containers/aardvark-dns', 'containers/image', 'containers/storage', 'containers/common',
      'containers/conmon', 'containers/podman-py', 'containers/bootc', 'containers/composefs',
      'interTwin-eu/interLink', 'interTwin-eu/vk-test-set', 'interTwin-eu/interlink-jhub',
      'interTwin-eu/interlink-slurm-plugin', 'interTwin-eu/interlink-docker-plugin',
      'interTwin-eu/interlink-helm-chart', 'interTwin-eu/interlink-monitoring-stack',
      'interTwin-eu/interlink-htcondor-plugin', 'interTwin-eu/interlink-kueue-plugin',
      'interTwin-eu/interlink-arc-plugin', 'interTwin-eu/interlink-unicore-plugin', 'aenix-io/etcd-operator',
      'aenix-io/talm', 'aenix-io/talos-bootstrap', 'aeniz-io/cozystack', 'aenix-io/kubernetes-in-kubernetes',
      'aenix-io/kubefarm', 'aenix-io/cozystack-website', 'aenix-io/cozy-proxy', 'aenix-io/cozystack-telemetry-server',
      'jozu-ai/kitops', 'aenix-io/cozystack-gitops-example', 'jozu-ai/gh-kit-setup', 'jozu-ai/daggerverse',
      'jozu-ai/pykitops', 'solo-io/gloo', 'kubernetes-purgatory/headlamp', 'nubificus/urunc',
      'streamnative/oxia', 'Azure/dalec', 'robusta-dev/holmesgpt', 'robusta-dev/homebrew-holmesgpt',
      'robusta-dev/holmesgpt-community-toolsets'
    )
  )
  and repo.name not in (
    'k3s-io/klog', 'k3s-io/containerd', 'k3s-io/cri-tools', 'k3s-io/etcd', 'k3s-io/flannel',
    'k3s-io/go-powershell', 'k3s-io/kubernetes', 'k3s-io/nocode'
  )
